[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Extends cargo to run the given command on multiple crates"
homepage = "https://github.com/imp/cargo-multi"
keywords = ["cargo", "subcommand", "multi"]
license = "APACHE-2.0/MIT"
name = "cargo-multi"
repository = "https://github.com/imp/cargo-multi.git"
version = "0.0.0"

[dependencies]
argparse = "0.2.1"
