[package]
name = "cargo-multi"
version = "0.0.0"
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Extends cargo to run the given command on multiple crates"
repository = "https://github.com/imp/cargo-multi.git"
homepage = "https://github.com/imp/cargo-multi"
keywords = ["cargo", "subcommand", "multi"]
license = "APACHE-2.0/MIT"

[dependencies]
